services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: papikos-kos:latest
    ports:
      - '8080:8080'
    networks:
      - papikos-network
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB} # Use service name 'postgres' as hostname
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Or validate, create, create-drop depending on your needs

    depends_on: # <-- Add this to ensure dependencies start first
      - postgres

  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - papikos-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  papikos-network:
    driver: bridge
